AdminUser.create(email: 'admin@example.com',
                 password: 'password',
                 password_confirmation: 'password')
User.create(email: 'user1@example.com',
            password: 'password',
            password_confirmation: 'password')
User.create(email: 'user2@example.com',
            password: 'password',
            password_confirmation: 'password')
FactoryGirl.create :organization,
                   status: Status.find_by_name('Active')
FactoryGirl.create :organization,
                   status: Status.find_by_name('Inactive')
FactoryGirl.create :sponsor,
                   sponsor_type: SponsorType.find_by_name('Individual')
FactoryGirl.create :sponsor,
                   sponsor_type: SponsorType.find_by_name('Organization')
FactoryGirl.create :partner,
                   province: Province.find_by_name('Homs')
FactoryGirl.create :partner,
                   province: Province.find_by_name('Aleppo')
FactoryGirl.create :orphan
FactoryGirl.create :orphan
FactoryGirl.create :orphan
