language: ruby
rvm:
- 2.1.2
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- bundle exec rake db:create
- bundle exec rake db:schema:load
script:
- bundle exec rake test_with_coveralls
