# to use byebug https://medium.com/@ddomachine/docker-and-ruby-on-rails-448ab8255f97
version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/osra
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true