<%
rerun = File.file?('rerun.txt') ? IO.read('rerun.txt') : ""
rerun_opts = rerun.to_s.strip.empty? ? "--format #{ENV['CUCUMBER_FORMAT'] || 'progress'} features" : "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} #{rerun}"
std_opts = "-r features --format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} --strict --tags ~@wip"
std_opts_aa = "-r features/aa -r features/support --format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} --strict --tags ~@wip_aa"
%>
default: <%= std_opts_aa %> features/aa
aa: <%= std_opts_aa %> features/aa
wip: --tags @wip:3 --wip features
wip_aa: --tags @wip_aa:3 --wip features/aa
rerun: <%= rerun_opts %> --format rerun --out rerun.txt --strict --tags ~@wip
