<%
rerun = File.file?('rerun.txt') ? IO.read('rerun.txt') : ""
rerun_opts = rerun.to_s.strip.empty? ? "--format #{ENV['CUCUMBER_FORMAT'] || 'progress'} features" : "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} #{rerun}"
std_opts = "-r features --format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} --strict --tags ~@wip"
std_opts_hq = "-r features_hq --format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} --strict --tags ~@wip_hq"
%>
default: <%= std_opts %> features
hq: <%= std_opts_hq %> features_hq
wip: --tags @wip:3 --wip features
wip_hq: --tags @wip_hq:3 --wip features_hq
rerun: <%= rerun_opts %> --format rerun --out rerun.txt --strict --tags ~@wip
