# Creating Default Provinces
Province.create(name: "Damascus & Rif Dimashq", code: 11)
Province.create(name: "Aleppo", code: 12)
Province.create(name: "Homs", code: 13)
Province.create(name: "Hama", code: 14)
Province.create(name: "Latakia", code: 15)
Province.create(name: "Deir Al-Zor", code: 16)
Province.create(name: "Daraa", code: 17)
Province.create(name: "Idlib", code: 18)
Province.create(name: "Ar Raqqah", code: 19)
Province.create(name: "Al Ḥasakah", code: 20)
Province.create(name: "Tartous", code: 21)
Province.create(name: "Al-Suwayada", code: 22)
Province.create(name: "Al-Quneitera", code: 23)
Province.create(name: "Outside Syria", code: 29)